### ISSUE TITLE
Player does not fall to the grass block when the 'D' key is pressed.

### ISSUE THREAD

**Issue by grumpybee100** [Grumpy-Games-Studios/run#13]

**Comment by grumpybee100** [comment]
Nope. Still occurs even after latest commit. @grumpycoder100

**Comment by grumpybee100** [comment]
I'll be making another branch. The second branch will be **only** for the desktop version, while the _master_ branch remains **only** for touchscreen devices. The two events for controls(keyboard + touchscreen) were conflicting each other, so new issues occurred. I'll close this issue in this branch and reopen the same one in the second one.

**Comment by grumpycoder100** [comment]
@grumpybee100 ,I have re-written the entire collision detection mechanism, and so far, everything's working great! I'll just finish the rest up, then the commit should be up.
