### ISSUE TITLE
BUG: Player unable to jump after landing on grass blocks.

### ISSUE THREAD

**Issue by grumpycoder100** [Grumpy-Games-Studios/run#14]

**Comment by grumpycoder100** [comment]
@grumpybee100 can you check this short fix out? Please report back ASAP.

**Comment by grumpybee100** [comment]
Sorry for the late reply. Was at a conference. Anyways, yes, it seems to be working great now. Player is able to jump from either of the grass blocks.

**Comment by grumpybee100** [comment]
Apparently your code is only valid for the first and second grass blocks, so I've made a new patch in attempt to actually fix this issue. My patch is only tested on the first three blocks. If it works, update me and I'll continue the patch for the rest of the blocks.

**Comment by grumpycoder100** [comment]
@grumpybee100 nice rewrite! No issues with collisions, player falls when not overlapping with the grass block. I think if this rewrite can actually work then you can merge this branch with the master branch. 👍

**Comment by grumpybee100** [comment]
Yeap, I'm continuing the rewrite since it's working fine now. Once all the changes are pushed then I'll merge, and close this issue.

**Comment by grumpybee100** [comment]
Fixed in latest commit.
