### ISSUE TITLE
Bug when attempting to jump

### ISSUE THREAD

**Issue by grumpycoder100** [Grumpy-Games-Studios/run#4]
To reproduce this bug, try tapping on the jump button, and notice that the character does not move/jump. Instead, it just moves up a few pixels per tap, and just stays there. Gonna need some help @grumpybee100 .

**Comment by grumpybee100** [comment]
I'll be starting a new temporary branch, just to do some testing about this issue. If I manage to get it done ASAP, then we can start on the first project already.

**Comment by grumpycoder100** [comment]
Fixed in the latest commit, as referenced above.
